---
- name: Prepare
  hosts: localhost
  tasks:
    - name: Delete a test IAM user
      amazon.aws.iam_user:
        name: "{{ iam_username }}"
        state: absent
      delegate_to: localhost

    - name: Delete a test IAM user secret
      # noqa: run-once[task]
      when: create_aws_secrets
      community.aws.secretsmanager_secret:
        name: "users/aws/{{ iam_username }}"
        state: absent
      delegate_to: localhost
      run_once: true
