---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: awsrotateiamkey01
    image: rockylinux:9
    pre_build_image: false
    privileged: false
    groups:
      - internal
  - name: awsrotateiamkey02
    image: rockylinux:9
    pre_build_image: false
    privileged: false
    groups:
      - internal
provisioner:
  name: ansible
  inventory:
    group_vars:
      internal:
        iam_username: testuser1
        aws_cli_user: awscliuser1
verifier:
  name: ansible
