---
lint: |
  set -e
  yamllint .
  ansible-lint -f full
dependency:
  name: galaxy
driver:
  name: containers
platforms:
  - name: t01
    image: rockylinux:9
    pre_build_image: false
    privileged: false
    groups:
      - internal
  - name: t02
    image: rockylinux:9
    pre_build_image: false
    privileged: false
    groups:
      - external
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        iam_username: testuser1
        users_map_data:
          testuser1: xyz01234
          testuser2: xyz56789
      internal:
        users_map_filename: /tmp/users_map
      # internal:
      #   aws_cli_user: testuser1
      # external:
      #   aws_cli_user: xyz01234
verifier:
  name: ansible
