---
- name: Verify
  hosts: all
  vars:
    iam_username: "testuser1"
    aws_cli_user: "awscliuser1"
  tasks:
    - name: Run awscli command as cli_user
      ansible.builtin.command:
        cmd: "/usr/local/bin/aws sts get-caller-identity --no-cli-pager"
      become: yes
      become_user: "{{ aws_cli_user }}"
      register: __awscli_output
      changed_when: false

    - name: Debug awscli output
      ansible.builtin.debug:
        var: __awscli_output.stdout
